### PR TITLE
Add support for private Gitiles git instances

### PR DESCRIPTION
**Pull request by csm10495**
Where I work, we use a private instance of Gerrit. These settings seem to work for getting urls to our code instance. I couldn't figure out a way to do multiple lines, so it just goes to the first line in that case.

Let me know what should be run to test, etc. Thanks.

### CODE REVIEW

**Comment by csm10495** [comment]
Going to rename this to support for Gitiles since I guess this is that component of Gerrit: https://gerrit.googlesource.com/gitiles/

**Comment by csm10495** [comment]
Got closer, with less tests failing and the extension seems to work for me. Not sure what's wrong :/

Here are the settings I used: 
```
    "gitweblinks.gitiles": [
        {
            "http": "https://git.company.com:1368/plugins/gitiles/",
            "ssh": "ssh://git.company.com:29419/"
        },
        {
            "http": "https://git.company.com:1368/plugins/gitiles/",
            "ssh": "ssh://<USERNAME>@git.company.com:29419/"
        }
    ]

```

A possible file url is like so: 
```
https://git.company.com:1368/plugins/gitiles/<PROJECT>/<REPO>+/<BRANCH_OR_COMMIT>/<PATH_TO_FILE

Or with a line number:

https://git.company.com:1368/plugins/gitiles/<PROJECT>/<REPO>+/<BRANCH_OR_COMMIT>/<PATH_TO_FILE#<LINE_NUM>
```
As far as I know there isn't multiline or column highlighting available.

The ssh clone url can be something like this (and it may or may not have the USER set):
```
ssh://<USER>@git.company.com:29419/<PROJECT>/<REPO>

<OR>

ssh://<USER>@git.company.com:29419/<PROJECT>/<REPO>.git
```

@reduckted any chance you can point me where I might be wrong?

**Comment by reduckted** [comment]
@csm10495 Thanks for the contribution! ❤️ 

You were pretty close with the configuration you were using. I've made a change to the "reverse" configuration which allows the extension to [open the file from a URL](https://github.com/reduckted/vscode-gitweblinks#open-the-file-from-a-link). It works for me on my very basic Gitiles server that I've set up, but if you could try it out as well, that would be great.

P.S. Don't worry about the build failing at the moment. For some reason, some unrelated tests have started failing. 😞

**Comment by csm10495** [comment]
Looks like it works for me! Thanks! Any chance for a merge/new version? :)

**Comment by reduckted** [comment]
> Any chance for a merge/new version? :)

Certainly! I've just published v2.4.0. It should be available on the marketplace shortly.

**Comment by csm10495** [comment]
Woot! Thanks!

**Pull request merged**
